# Generated by Django 5.0.3 on 2024-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
